version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: education
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: golang_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: mysql_container
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: education
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  db_data: